version: '3.7'
services:
   mysql:
    image: mysql:8
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: foatball-league
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      USER: 1000
   
   node:
      image: node:14.4.0
      hostname: league-api
      ports:
        - "3000:3000"
        - "1235:1235"
      volumes:
        - ../:/var/www
      working_dir: /var/www
      command: node ./index.js
   
